packages:
  - tools/**
  - libs/**
  - apps/**
  - e2e/**
  - '!**/dist/**'
  - '!**/dist-spec/**'
  - '!**/build/**'
  - '!**/tmp/**'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
