name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm i
      - run: pnpm run format:check
      - run: pnpm run lint:affected:ci
      - run: pnpm run test:affected:ci
      - run: pnpm run build:affected:ci
