name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          npm i -g corepack@${{ env.CV_COREPACK_VERSION }}
          corepack enable
        env:
          # renovate: datasource=npm depName=corepack
          CV_COREPACK_VERSION: '0.32.0'

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm i

      - uses: ./.github/actions/install-playwright

      - uses: ./.github/actions/cache-firebase-emulators

      - run: echo "NX_VERBOSE_LOGGING=${{ runner.debug && true || false }}" >> "$GITHUB_ENV"

      - run: pnpm nx affected -c ci -t e2e-pw

      - run: pnpm nx report

      - run: pnpm nx sync:check

      - run: pnpm nx format:check

      - run: >
          pnpm nx affected -c ci -t
          lint
          lint-eslint
          typecheck
          typecheck-tsc

      - run: >
          pnpm nx affected -c ci -t
          build
          build-tsc
          build-angular
          build-ng-packagr

      - run: >
          pnpm nx affected -c ci -t
          test
          test-vitest
          test-angular

      - run: >
          pnpm nx affected -c ci -t
          e2e
          e2e-pw
