name: lint-pr-title

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i

      - run: pnpm nx run @robby-rabbitman/cv-tools-commitlint:commitlint
        env:
          CV_TOOLS_COMMITLINT_TEXT: ${{ github.event.pull_request.title }}
